--- # Installing Java & Apache Tomcat container

- hosts: webservers
  become: true
  become_method: sudo
  tasks: 
        - name: Install java on RedHat
          yum: 
                name: java
                state: installed
          when: ansible_os_family == "RedHat"

        - name: download Tomcat
          get_url:
                  url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.63/bin/apache-tomcat-9.0.63.tar.gz
                  dest: /opt

        - name: extract tomcat
          unarchive:
                    src: /opt/apache-tomcat-9.0.63.tar.gz
                    dest: /opt
                    remote_src: yes

        - name: add executable permissions
          file:
                path: /opt/apache-tomcat-9.0.63/bin/startup.sh
                mode: 0777

        - name: start tomcat service
          shell: nohup ./startup.sh
          args:
                chdir: /opt/apache-tomcat-9.0.63/bin    

                  #- name: Start and enable tomcat
                  #service:
                  #daemon_reload: yes
                  #name: tomcat
                  #state: started
                  #enabled: yes
                  # when: ansible_service_mgr == "systemd"      
